name = "stasher-api"
main = "worker.ts"
compatibility_date = "2023-05-18"
account_id = "5315a5297c25808a48518923d6fe9d90"

[observability]
enabled = true

[[durable_objects.bindings]]
name = "STASHER_DO"
class_name = "StasherDO"

[[migrations]]
tag = "v1"
new_classes = [ "StasherDO" ]